# Generated by Django 2.1.4 on 2018-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.PositiveIntegerField(choices=[(1, 'кг.'), (2, 'г.'), (3, 'шт.')], default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
