# Generated by Django 2.1.4 on 2018-12-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20181220_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='absolute_usage',
        ),
        migrations.AddField(
            model_name='component',
            name='usage',
            field=models.IntegerField(choices=[(1, 'на 1 шт.'), (2, 'на 1 кг.')], default=2),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.PositiveIntegerField(choices=[(1, 'кг.'), (2, 'г.'), (3, 'шт.'), (4, 'л.')], default=1),
        ),
    ]
