# Generated by Django 2.1.4 on 2018-12-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_auto_20181220_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(),
        ),
    ]
